#!/bin/bash

export LC_NUMERIC=en_US.utf-8

# Description: Script generating input files
#              off random float numbers used 
#              in standardDeviation.py

# Usage: ./generate

for i in 10 100 1000; do 
    generate=$(awk -v n=$i -v min=-500 -v max=500 -v seed="$RANDOM" '
            BEGIN { srand(seed); 
                    for (i=1; i<=n; i++)
                        printf("%.2f%s", min+rand()*(max-min+1),
                                         (i%100==0) ? "\n" : " ");
            }')
    FILE="data_$i.txt"
    echo "$generate" > "$FILE"  
done    
